### ISSUE TITLE
Migrate nightly job from ember-m3

### ISSUE THREAD

**Issue by rwjblue** [hjdivad/nyx.js#1]
Migrate https://github.com/hjdivad/ember-m3/blob/master/.github/workflows/nightly.yml and https://github.com/hjdivad/ember-m3/blob/master/bin/report-nightly-failure.js from ember-m3 into here, and update ember-m3 to use the new versions.

**Comment by hjdivad** [comment]
https://github.com/hjdivad/ember-m3/issues/586
